
--THIS TRIGGER CHANGES THE PRESCRIPTION PRICE AFTER A PAYMENT HAS BEEN MADE BY THE PATIENT
CREATE or REPLACE TRIGGER ChangePrescriptionPriceAfterPatientPayment
    AFTER INSERT ON HealthCareManagement_PATIENTPAYMENT
    For Each Row
BEGIN
    UPDATE  HealthCareManagement_PRESCRIPTIONBALANCE
    SET     PATIENTBALANCE=PATIENTBALANCE-:NEW.AMOUNT
    WHERE   PRESCRIPTION_ID=:NEW.PRESCRIPTION_ID;
END;

--THIS TRIGGER CHANGES THE PRESCRIPTION PRICE AFTER A PAYMENT HAS BEEN MADE BY THE INSURANCE COMPANY
CREATE or REPLACE TRIGGER ChangePrescriptionPriceAfterInsurancePayment
    AFTER INSERT ON HealthCareManagement_INSURANCEPAYMENT
    For Each Row
BEGIN
    UPDATE  HealthCareManagement_PRESCRIPTIONBALANCE
    SET     INSURANCEBALANCE=INSURANCEBALANCE-:NEW.AMOUNT
    WHERE   PRESCRIPTION_ID=:NEW.PRESCRIPTION_ID;
END;


--TEST STATEMENTS:
SELECT * FROM HealthCareManagement_PRESCRIPTIONBALANCE;
INSERT INTO HealthCareManagement_PATIENTPAYMENT (PAYMENT_ID, PAYMENT_DATE, AMOUNT, PATIENT_ID, PRESCRIPTION_ID)
        VALUES ('PAY001', TO_DATE('2023-06-15', 'YYYY-MM-DD'), 15.00, 'PAT001', 'PRSC001');
INSERT INTO HealthCareManagement_INSURANCEPAYMENT (PAYMENT_ID, PAYMENT_DATE, AMOUNT, INSURANCE_ID, PRESCRIPTION_ID)
        VALUES ('PAY001', TO_DATE('2023-06-15', 'YYYY-MM-DD'), 2.00, 'INS001', 'PRSC001');      
SELECT * FROM HealthCareManagement_PRESCRIPTIONBALANCE;

--FIRST SELECT:
--PRESCRIPTION_ID   PATIENT_ID      INSURANCE_ID   INSURANCEBAL PATIENTBAL 
--PRSC001	        PAT001	        INS001	        2.5	        22.5
--PRSC002	        PAT002	        INS002	        3.75	    11.25
--PRSC003	        PAT003	        INS003	        12	        18
--PRSC004	        PAT004	        INS004	        3.3	        18.7
--PRSC005	        PAT005	        INS005	        4.5	        40.5
--PRSC006	        PAT006	        INS006	        0	        10

--AFTER INSERT:
--PRESCRIPTION_ID   PATIENT_ID      INSURANCE_ID   INSURANCEBAL PATIENTBAL 
--PRSC001	        PAT001	        INS001	        0.5	        7.5
--PRSC002	        PAT002	        INS002	        3.75	    11.25
--PRSC003	        PAT003	        INS003	        12	        18
--PRSC004	        PAT004	        INS004	        3.3	        18.7
--PRSC005	        PAT005	        INS005	        4.5	        40.5
--PRSC006	        PAT006	        INS006	        0	        10


